### ISSUE TITLE
Write benchmarks

### ISSUE THREAD

**Issue by Thomasdezeeuw** [Thomasdezeeuw/mio-st#47]
Write benchmarks for the following:

- [ ] Duplicated kqueue file descriptor vs. none-duplicated, see pr #45.
- [ ] Timer space event structure, see issue #2.
- [ ] User space events, see issue #25.
